#!/usr/bin/env bash
#
# git-cheat: gerador de html
#
# Copyright (C) 2015 Silvio Rhatto
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Parâmetros
BASEDIR="$(pwd)"
DATA="$BASEDIR/data"
OUTPUT="$BASEDIR/output"
PANDOC_OPTS="${PANDOC_OPTS:=--template=default.html5}"

echo '       _ _          _                _   '
echo '  __ _(_) |_    ___| |__   ___  __ _| |_ '
echo ' / _` | | __|  / __|  _ \ / _ \/ _` | __|'
echo '| (_| | | |_  | (__| | | |  __/ (_| | |_ '
echo ' \__, |_|\__|  \___|_| |_|\___|\__,_|\__|'
echo ' |___/   '
echo '                                                      '
echo '                                      gerador de html!'
echo '                                                      '
# texto gerado por http://www.network-science.de/ascii/

echo "Limpando a versão anterior..."
rm -rf $OUTPUT || exit 1

echo "Garantindo a existência das pastas necessárias..."
mkdir -p $OUTPUT || exit 1

echo "Copiando a estrutura de pastas..."
rsync -qav $DATA/ $OUTPUT/ || exit 1

echo "Convertendo todos arquivos Markdown para HTML..."
find $OUTPUT -name '*md' -exec pandoc $PANDOC_OPTS -o {}.html {} \; || exit 1

echo "Limpando arquivos markdown..."
find $OUTPUT -name '*mdwn' -exec rm {} \; || exit 1

echo "Corrigindo o nome dos arquivos gerados..."
find $OUTPUT -name '*.html' -exec rename 's/\.mdwn.html$/.html/' {} \; || exit 1

echo "Feito! Tenha um bom dia :)"
