#!/usr/bin/env bash
#
# git-cheat: gerador de html
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Parâmetros
BASEDIR="$(pwd)"
DATA="$BASEDIR/data"
OUTPUT="$BASEDIR/output"
TEMP="$BASEDIR/tmp"
PANDOC_HOME="$(pwd)/pandoc-2.3"
PANDOC_OPTS="${PANDOC_OPTS:=--template=default.html5}"

echo '       _ _          _                _   '
echo '  __ _(_) |_    ___| |__   ___  __ _| |_ '
echo ' / _` | | __|  / __|  _ \ / _ \/ _` | __|'
echo '| (_| | | |_  | (__| | | |  __/ (_| | |_ '
echo ' \__, |_|\__|  \___|_| |_|\___|\__,_|\__|'
echo ' |___/   '
echo '                                                      '
echo '                                      gerador de html!'
echo '                                                      '
# texto gerado por http://www.network-science.de/ascii/

echo "Limpando a versão anterior..."
rm -rf $OUTPUT || exit 1

echo "Garantindo a existência das pastas necessárias..."
mkdir -p $TEMP || exit 1

echo "Copiando a estrutura de pastas..."
find $DATA/ -type d -print0 |  xargs -0 -L1 -i mkdir -p "tmp/{}" || exit 1
#find $DATA -type d -print0 | echo {} \;
#rsync -qav $DATA/ $OUTPUT/ || exit 1

echo "Convertendo todos arquivos Markdown para HTML..."
find $DATA -name '*md' -exec $PANDOC_HOME/pandoc $PANDOC_OPTS -o $TEMP/{}.html {} \; || exit 1

echo "Limpando arquivos temporarios..."
mv $TEMP/$DATA $OUTPUT && rm -rf $TEMP || exit 1

echo "Corrigindo o nome dos arquivos gerados..."
#find $OUTPUT -name '*.html' -exec rename 's/\.md.html$/.html/' {} \; || exit 1
#echo {} \;
echo "Feito! Tenha um bom dia :)"
